# Generated by Django 3.0.5 on 2020-05-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modelling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='topics',
            field=models.TextField(default='[]'),
            preserve_default=False,
        ),
    ]
