# Generated by Django 3.0.5 on 2020-05-23 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('algorithm', models.CharField(max_length=100)),
                ('all_data', models.TextField()),
                ('selected_document_index', models.IntegerField()),
                ('selected_document_name', models.CharField(max_length=1024)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_project', to='project.Project')),
            ],
        ),
    ]
